### ISSUE TITLE
System.ArgumentException: 'Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.'

### ISSUE THREAD

**Issue by FlayInAHook** [TheKillerey/Avatar#4]
While trying to save the mapgeo file I get this error which I don't understand unlike the others I got 

System.ArgumentException
  HResult=0x80070057
  Message=Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at LeagueToolkit.Helpers.Memory.CopyStructureToBuffer[T](Byte[] bufer, Int32 offset, T structure)
   at LeagueToolkit.IO.MapGeometry.MapGeometryVertex.ToArray(Int32 vertexSize)
   at LeagueToolkit.IO.MapGeometry.MapGeometry.GenerateVertexBuffers(List`1 vertexElementGroups)
   at LeagueToolkit.IO.MapGeometry.MapGeometry.Write(Stream stream, UInt32 version, Boolean leaveOpen)
   at LeagueToolkit.IO.MapGeometry.MapGeometry.Write(String fileLocation, UInt32 version)
   at Avatar.MainWindow.OnMapgeoFileSave_Click(Object sender, RoutedEventArgs e) in C:\Users\Tim\Desktop\CustomSkin\Avatar\Avatar\MainWindow.xaml.cs:line 1417
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
)

**Comment by FlayInAHook** [comment]
**REDACTED**
These are the files that I'm using.

**Comment by FlayInAHook** [comment]
Well turns out the obj settings form my maya export werent alligned properly with the way you should export using blender. 
So yeah I fixed that and it works like a charm. Thank you so much for making this!
